# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test1 do
    gradle(task: "test")
  end
  lane :test do
    # Run your Flutter tests
    sh("flutter test")
  end

  desc "Increment Version"
    lane :increment_version do
        latest_release = firebase_app_distribution_get_latest_release(
          app: "1:337613462775:android:a0562f974110a561b907f2"
        )
        increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :beta1 do
      increment_version_code(
          gradle_file_path: "./app/build.gradle",
      )
  end

  desc "Build"
  lane :build do
    Dir.chdir '../..' do
      sh("flutter","build","apk","--flavor","prodGlobal","-t" ,"lib/mains/main_global_prod.dart")
    end
  end

  desc "Increment Version"
  lane :increment_version_firebase do
      latest_release = firebase_app_distribution_get_latest_release(
        app: "1:337613462775:android:a0562f974110a561b907f2",
        firebase_cli_token:"1//0gpNf1dSBGjKzCgYIARAAGBASNwF-L9IrlMxpvT_RX--bKUHpFoIxlgJxeoJnF4Z8vFir9kMSKV5qyaloVV6O-XORXErf_vIToQE",
      
      )
      increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta2 do
    increment_version_firebase
    build
    print Dir.pwd
    firebase_app_distribution(
      #1//0gyURlXKUChfsCgYIARAAGBASNwF-L9IrYxMzphO9djvnPRkmSl_BsYz9qoEK6k5nadDwTDd-ULOLwYVJx_dA5JPpOF8Q_F_LpbI
      firebase_cli_token:${{secrets.FIREBASE_CLI_TOKEN}},
      app: "1:337613462775:android:a0562f974110a561b907f2",
      groups: "group-one",
      release_notes: "Lots of new avatars to try out!",
      android_artifact_type: "APK",
      apk_path: "../build/app/outputs/apk/prodGlobal/release/app-prod-global-release.apk",
    )
  end

  desc "beta 3"
  lane :beta3 do
    firebase_app_distribution_get_udids
  end
end
