name: Share Variables Between Jobs

on:
  workflow_dispatch:  # This allows manual triggering of the workflow
    inputs:
      some_value:
        description: 'Enter a value to pass between jobs'
        required: true
        default: 'default_value'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      VALUE: ${{ steps.set_output.outputs.value }} # Share the output of step

    steps:
      - name: Set a variable in Job 1
        id: set_output  # Add an ID to the step for reference
        run: |
          # Assign the input value to a variable
          VALUE="${{ github.event.inputs.some_value }}"
          
          # Set the value as an output
          echo "::set-output name=value::$VALUE"

  job2:
    runs-on: ubuntu-latest
    needs: job1  # Ensure job2 runs after job1
    steps:
      - name: Use the variable from Job 1 in Job 2
        run: |
          # Access the value passed from Job 1 using job outputs
          echo "Value passed from Job 1: ${{ needs.job1.outputs.VALUE }}"
