name: Share Variables Between Jobs

on:
  workflow_dispatch:  # This allows manual triggering of the workflow
    inputs:
      some_value:
        description: 'Enter a value to pass between jobs'
        required: true
        default: 'default_value'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set a variable in Job 1
        run: |
          # Assign the input value to a variable
          VALUE="${{ github.event.inputs.some_value }}"
          
          # Output the value
          echo "Value in Job 1: $VALUE"
          
          # Write the value to GITHUB_ENV to pass it to other jobs
          echo "VALUE=$VALUE" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest
    needs: job1  # This ensures job2 waits for job1 to finish
    steps:
      - name: Use the variable from Job 1 in Job 2
        run: |
          # Access the value shared from Job 1
          echo "Value passed from Job 1: $VALUE"
