name: fastlane-publish
on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor'     
        required: true
        default: 'devGlobal'
        type: choice
        options:
          - prodGlobal
          - stgGlobal
          - devGlobal
      type:
        description: 'Build Type - release/debug'     
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      release_notes:
        description: 'Release Notes'
      version_name:
        description: 'Version Name  [major.minor.patch]'
jobs:
  build:
    runs-on: macos-latest
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
    
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
      # Get flutter dependencies.
      - run: flutter pub get
      - uses: actions/checkout@v2
      - run: |
          curl -X GET 'https://qa-vault.seasam.org/v1/sys/internal/ui/mounts/secret' --header 'X-Vault-Token: hvs.CAESIKp3rwo0NTzTPdnj32-uIbKUQFzzugNDSNP5Wllf_rapGh4KHGh2cy5kR2tGZTI1bEhTZG9wZmJGRTEzMERFTHc' > ../country_keys/uk/vault.txt
          cat ../country_keys/uk/vault.txt
          ls ../country_keys/uk/

          cd  android

          echo "fastlane publishBuild flavor:${{ github.event.inputs.flavor }} release_notes:${{ github.event.inputs.release_notes }} type:${{ github.event.inputs.type }}"
        #  fastlane publishBuild flavor:${{ github.event.inputs.flavor }} release_notes:"${{ github.event.inputs.release_notes }}" type:${{ github.event.inputs.type }} version_name:${{ github.event.inputs.version_name }}
        #env:
        #  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
