name: ftp
on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor'     
        required: true
        default: 'devGlobal'
        type: choice
        options:
          - prodGlobal
          - stgGlobal
          - devGlobal
      type:
        description: 'Build Type - release/debug'     
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      release_notes:
        description: 'Release Notes'  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: pwd
        run: |
         pwd
         ls
      - name: Generating FTP files
        run: |
          mkdir scic_app_distribution
          cd scic_app_distribution

          mkdir cicd
          curl -X GET "https://raw.githubusercontent.com/AbhijithKonnayil/navigation/refs/heads/main/release_list_1.json" > cicd/release_list.json

          mkdir cicd/build_apks
          #cp source build_apks/
          touch cicd/build_apks/test.txt

          #ls
          ls cicd

          cat cicd/release_list.json
          
          VERSION_NAME="1.1.1"
          VERSION_CODE="1234"
          TIMESTAMP=$(date "+%F %T %A" )
          SIZE="12 MB"
          BRANCH="release_senh_17_rc_1"
          RELEASE_NOTES="this is release notes"
          LINK="../build_apks/"
          APK_NAME="apk name"
          echo $TIMESTAMP
          cd ..
          sh release.sh version_name="$VERSION_NAME" version_code="$VERSION_CODE" timestamp="$TIMESTAMP" size="$SIZE" branch="$BRANCH" release_notes="$RELEASE_NOTES" link="$LINK" apk_name="$APK_NAME"

          cat scic_app_distribution/cicd/release_list.json

      - name: FTP-Deploy-Action-Release-List
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER_CN }}
          username: ${{ secrets.FTP_USERNAME_CN }}
          password: ${{ secrets.FTP_PASSWORD_CN }}
          port: ${{ secrets.FTP_PORT_CN }}
          local-dir: ${{ github.workspace }}/scic_app_distribution/cicd/
          server-dir: /cicd/
      - name: FTP-Deploy-Action-Build
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER_CN }}
          username: ${{ secrets.FTP_USERNAME_CN }}
          password: ${{ secrets.FTP_PASSWORD_CN }}
          port: ${{ secrets.FTP_PORT_CN }}
          local-dir: ${{ github.workspace }}/scic_app_distribution/cicd/build_apks/
          server-dir: /cicd/build_apks/
