name: ip
on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor'     
        required: true
        default: 'devGlobal'
        type: choice
        options:
          - prodGlobal
          - stgGlobal
          - devGlobal
      type:
        description: 'Build Type - release/debug'     
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      release_notes:
        description: 'Release Notes'  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          echo "IP"
          dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com
          pwd
          ls
          echo "---"
          curl  -X GET 'https://raw.githubusercontent.com/AbhijithKonnayil/navigation/main/android/props.encode.txt'
        #env:
        #  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
