name: TAG
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor'     
        required: true
        default: 'devGlobal'
        type: choice
        options:
          - prodGlobal
          - stgGlobal
          - devGlobal
      type:
        description: 'Build Type - release/debug'     
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      release_notes:
        description: 'Release Notes'  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          echo "TAG CREATION"
      - name: Set env
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          REGEX="^v[0-9]+\.[0-9]+\.[0-9]+\+[0-9]+-(stg|prod|dev)-(global|india|brazil)-(release|debug)$"

          # Check if the tag name matches the regex
          if [[ $TAG_NAME =~ $REGEX ]]; then
            echo "Tag format is valid: $TAG_NAME"
          else
            echo "INVALID FORMAT"
            exit 1 # Exit with error code 1 to stop the workflow if format is invalid
          fi

          # Strip the 'v' prefix
          VERSION_NAME=$(echo $TAG_NAME | cut -d'+' -f1 | cut -d'v' -f2)

          # Extract the version code
          VERSION_CODE=$(echo $TAG_NAME | cut -d'+' -f2 | cut -d'-' -f1)

          # Extract the environment
          ENV=$(echo $TAG_NAME | cut -d'+' -f2 | cut -d'-' -f2)

          # Extract the country
          COUNTRY=$(echo $TAG_NAME | cut -d'+' -f2 | cut -d'-' -f3)

          # Extract the release type
          TYPE=$(echo $TAG_NAME | cut -d'+' -f2 | cut -d'-' -f4)

          #TAG_MESSAGE=$(git for-each-ref refs/tags/$TAG_NAME --format="%(contents)")


          # Output the extracted variables
          echo "VERSION_NAME=$VERSION_NAME"
          echo "VERSION_CODE=$VERSION_CODE"
          echo "ENV=$ENV"
          echo "COUNTRY=$COUNTRY"
          echo "TYPE=$TYPE"

          # Set outputs for use in other steps
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "COUNTRY=$COUNTRY" >> $GITHUB_ENV
          echo "TYPE=$TYPE" >> $GITHUB_ENV
          #echo "Tag Message: $TAG_MESSAGE"

      - name: Use extracted values
        run: |
          echo "Version Name: $VERSION_NAME"
          echo "Version Code: $VERSION_CODE"
          echo "Environment: $ENV"
          echo "Country: $COUNTRY"
          echo "Type: $TYPE"